### ISSUE TITLE
How do I restrict the letters library to just my development environment?

### ISSUE THREAD

**Issue by marcamillion** [davejacobs/letters#17]
I tried this in my `application.rb`

`if defined?(Bundler)
  Bundler.require(*Rails.groups(:assets => %w(development test)))
    require "letters/patch/rails"(*Rails.groups(:assets => %w(development test)))
end`

But that threw an error on Heroku.

Any thoughts on how I might get this to not conflict with Heroku, but not force me to comment out when I am pushing to Heroku?

Thanks!

**Comment by davejacobs** [comment]
This should be fixed!

Try out the following to disable Letters in whatever environment you choose:

``` ruby
    Letters.config do
      all :disable => true
    end
```
